@url = http://localhost:6097
@id = 66293c7734d95bc2886aad7a

GET {{url}}

###
POST {{url}}/auth/signup
Content-Type: application/json

{
    "password":"abcdef",
    "email":"hardikgarg3085@gmail.com"

}

###
POST {{url}}/auth/signin
Content-Type: application/json

{
    "password":"abcdef",
    "email":"hardikgarg3085@gmail.com"

}