@url = http://localhost:6097
@id = 662fd293911438e972d27c96

GET {{url}}

###
POST {{url}}/mauth/signup
Content-Type: application/json

{
    "password":"abcdef",
    "mobile":"9215503085"

}

###
POST {{url}}/connectToDb
Content-Type: application/json

{

}

###
GET {{url}}/mauth/otp/9215503085